name: Hola mundo
on:
  push:
    branches: [ master ]
jobs:
  Mi-primer-job:
    name: Mi primer job
    runs-on: [ubuntu-latest, windows-latest, macOS-latest]
    outputs:
      salida: ${{ steps.imprimir.outputs.respuesta }}
    steps:
    - name: Imprimir
      id: imprimir
      env:
        MI_VARIABLE: Hola mundo
      run: echo "::set-output name=respuesta::${MI_VARIABLE}"

          
